### ISSUE TITLE
BUG: Problem with custom domain

### ISSUE THREAD

**Issue by jdauphant** [SocialGouv/dashlord-report-action#38]
The code isn't made for custom domain.
For example : https://dashlord.incubateur.net/

All resssource is releative to a path instead of being relative.

**Comment by revolunet** [comment]
In the action you can try:

```yaml
uses: SocialGouv/dashlord-report-action@master
with:
  public-url: /
```
